# Generated by Django 4.2.3 on 2023-08-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='time',
        ),
    ]
